apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omero
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: shared-standard
  volumeMode: Filesystem

