kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
  name: omero-server
  labels:
    app: omero-server
    app.kubernetes.io/component: omero-server
    app.kubernetes.io/instance: omero-server
    app.kubernetes.io/name: omero-server
    app.kubernetes.io/part-of: omero-server
    app.openshift.io/runtime-namespace: core-omero-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omero-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omero-server
        deploymentconfig: omero-server
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: omero
          persistentVolumeClaim:
            claimName: omero
#        - name: opt-omero-server-var
#          persistentVolumeClaim:
#            claimName: opt-omero-server-var
        - name: cap-omero
          persistentVolumeClaim:
            claimName: cap-omero
        - name: omero-server-grid-config
          persistentVolumeClaim:
            claimName: omero-server-grid-config
#        - name: omero-home
#          persistentVolumeClaim:
#            claimName: omero-home
        - name: 60-db
          configMap: 
            name: 60-db-cf
      initContainers:
        - name: init-copy-files
          image: registry.k8s.gu.se/openshift/omero-server:1.1
          command: ['sh', '-c', 'cp -rn /build_tmp/* /opt/omero/server/OMERO.server/', 'cp -rn /build_tmp2/* /OMERO/']
          volumeMounts:
            - mountPath: /opt/omero/server/OMERO.server
              name: omero-server-grid-config
            - mountPath: /OMERO
              name: cap-omero
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: omero-server
          env:
            - name: CONFIG_omero_db_user
              value: userVKX
            - name: CONFIG_omero_db_pass
              value: MfVoE7cdMLgUJPI4
            - name: CONFIG_omero_db_host
              value: postgresql
            - name: CONFIG_omero_db_name
              value: omero
            - name: ROOTPASS
              value: testar
            - name: CONFIG_omero_Ice_IPv6
              value: '0'
          ports:
            - containerPort: 4063
              protocol: TCP
            - containerPort: 4064
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: omero
              mountPath: /omero
#            - name: opt-omero-server-var
#              mountPath: /opt/omero/server/OMERO.server/var
            - name: cap-omero
              mountPath: /OMERO
            - name: omero-server-grid-config
              mountPath: /opt/omero/server/OMERO.server
            - name: 60-db
              mountPath: /startup/60-database.sh
              subPath: 60-database.sh
#            - name: omero-home
#              mountPath: /omero_home
          terminationMessagePolicy: File
          image: registry.k8s.gu.se/openshift/omero-server:1.1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
