apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-opt-omero
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: 
  volumeMode: Filesystem

