apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cap-omero
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: shared-standard
  volumeMode: Filesystem

