kind: Deployment
apiVersion: apps/v1
metadata:
  name: omero-server
  labels:
    app: omero-server
    app.kubernetes.io/component: omero-server
    app.kubernetes.io/instance: omero-server
    app.kubernetes.io/name: omero-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omero-server
  template:
    metadata:
      labels:
        app: omero-server      
    spec:
      volumes:
        - name: omero
          persistentVolumeClaim:
            claimName: server-omero
        - name: cap-omero
          persistentVolumeClaim:
            claimName: server-cap-omero
        - name: opt-omero
          persistentVolumeClaim:
            claimName: server-opt-omero
        - name: 60-db
          configMap: 
            name: 60-db-cf
            defaultMode: 493
        - name: 01-gu-config
          configMap: 
            name: 01-gu-config.omero
            defaultMode: 493
        - configMap:
            defaultMode: 493
          name: server-figure-to-pdf
            name: server-figure-to-pdf
      initContainers:
        - name: init-copy
          image: registry.k8s.gu.se/openshift/omero-server:1.7
          command: ["/bin/bash","-c"]
          args: 
              - |
                #/bin/sh              
                mkdir -p /mnt/opt
                mkdir -p /mnt/cap
                cp -r /opt/omero/server/OMERO.server/* /mnt/opt
                cp -rn /OMERO/D* /mnt/cap
                cp -rn /OMERO/F* /mnt/cap
                cp -rn /OMERO/Man* /mnt/cap
                cp -rn /OMERO/Pix* /mnt/cap
                cp -rn /OMERO/Thu* /mnt/cap
          volumeMounts:
            - name: opt-omero
              mountPath: /mnt/opt
            - name: cap-omero
              mountPath: /mnt/cap
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: omero-server
          env:
            - name: CONFIG_omero_db_user
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRESQL_USER
            - name: CONFIG_omero_db_pass
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRESQL_PASSWORD
            - name: CONFIG_omero_db_host
              value: change_me
            - name: CONFIG_omero_db_name
              value: change_me
            - name: ROOTPASS
              value: hejhej123
            - name: CONFIG_omero_Ice_IPv6
              value: '0'
          ports:
            - containerPort: 4063
              protocol: TCP
            - containerPort: 4064
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: omero
              mountPath: /omero
            - name: cap-omero
              mountPath: /OMERO
            - name: opt-omero
              mountPath: /opt/omero/server/OMERO.server
            - name: 60-db
              mountPath: /startup/60-database.sh
              subPath: 60-database.sh
            - name: 01-gu-config
              mountPath: /opt/omero/server/config/01-gu-config.omero
              subPath: 01-gu-config.omero
            - mountPath: /opt/omero/serer/OMERO.server/lib/scripts/omero/figure_scripts/Figure_To_Pdf.py
              name: server-figure-to-pdf
              subPath: Figure_To_Pdf.py
          terminationMessagePolicy: File
          image: registry.k8s.gu.se/openshift/omero-server:1.7
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
