apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-logs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: 
  volumeMode: Filesystem
