apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-slash-cache
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: 
  volumeMode: Filesystem
