apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-opt-omero-web
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: shared-standard
  volumeMode: Filesystem
