apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: omero-web
    app.kubernetes.io/component: omero-web
    app.kubernetes.io/instance: omero-web
    app.kubernetes.io/name: omero-web
  name: omero-web    
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: omero-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:      
      labels:
        app: omero-web
    spec:
      containers:
      - image: URL-TO-IMAGE
        imagePullPolicy: Always
        name: omero-web
        ports:
        - containerPort: 4080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/omero/web/
          name: opt-omero-web
        - mountPath: /omero
          name: omero-web
        - mountPath: /opt/omero/web/config/omeroweb-config.omero
          name: omeroweb-config-omero
          subPath: omeroweb-config.omero
        - mountPath: /startup/50-config.py
          name: 50-config-py
          subPath: 50-config.py
        - mountPath: /opt/omero/web/OMERO.web/var/django_secret_key
          name: django-secret-key
          subPath: django_secret_key
        - mountPath: /opt/omero/web/config/oauth-providers.yaml
          name: oauth-providers
          subPath: oauth-providers.yaml
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - |
          cp -rn /build_tmp2/* /opt/omero/web/
        command:
        - /bin/bash
        - -c
        image: URL-TO-IMAGE
        imagePullPolicy: IfNotPresent
        name: init-copy-files
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/omero/web/
          name: opt-omero-web
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: opt-omero-web
        persistentVolumeClaim:
          claimName: web-opt-omero-web
      - name: omero-web
        persistentVolumeClaim:
          claimName: web-omero-web
      - configMap:
          defaultMode: 493
          name: omeroweb-config.omero
        name: omeroweb-config-omero
      - configMap:
          defaultMode: 493
          name: 50-config.py
        name: 50-config-py
      - configMap:
          defaultMode: 493
          name: oauth-providers.yaml
        name: oauth-providers
      - name: django-secret-key
        secret:
          defaultMode: 420
          secretName: django-secret-key